# Generated by Django 5.0.6 on 2025-01-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reference', verbose_name='Organization (if any)'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.TextField(choices=[('client', 'Client'), ('service', 'Service company')], default='not specified', max_length=120, verbose_name='User type'),
        ),
    ]
