# Generated by Django 5.0.6 on 2025-01-12 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myuser_user_ref_alter_myuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='user',
        ),
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_client', related_query_name='machines_client', to='main.reference'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_type',
            field=models.TextField(choices=[('service', 'Service company'), ('client', 'Client'), ('machine_model', ' Machine model'), ('engine_model', 'Engine model'), ('transmission_model', 'Transmission model'), ('steerable_bridge_model', 'Steerable bridge model'), ('main_bridge_model', 'Main bridge model'), ('not_specified', 'not specified'), ('failure_node', 'Failure node'), ('recovery_method', 'Recovery method'), ('maintenance_type', 'Maintenance type')], default='not specified', max_length=120, verbose_name='Reference type'),
        ),
    ]
