# Generated by Django 5.0.6 on 2025-01-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_machine_user_machine_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ref', related_query_name='maintenancs_ref', to='main.reference'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reference', verbose_name='Organization or IP'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_ref', related_query_name='reclamations_ref', to='main.reference'),
        ),
    ]
