# Generated by Django 5.0.6 on 2025-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_maintenance_operating_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='refuse_date',
            field=models.DateTimeField(),
        ),
    ]
