# Generated by Django 5.0.6 on 2025-01-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reclamation_recovery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='machine_downtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
