# Generated by Django 5.0.6 on 2025-01-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_reclamation_machine_downtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_service', related_query_name='machines_service', to='main.reference'),
        ),
    ]
