# Generated by Django 5.0.6 on 2025-01-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_machine_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='mt_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mt_company_ref', related_query_name='mt_companies_ref', to='main.reference'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ref', related_query_name='maintenance_ref', to='main.reference'),
        ),
    ]
