# Generated by Django 5.0.6 on 2025-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_reference_ref_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='machine_downtime',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
