# Generated by Django 5.0.6 on 2025-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reclamation_machine_downtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='machine_downtime',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.TextField(choices=[('client', 'Client'), ('service', 'Service company'), ('manager', 'Manager')], default='not specified', max_length=120, verbose_name='User type'),
        ),
    ]
