# Generated by Django 5.0.6 on 2025-02-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_reclamation_machine_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_date',
            field=models.PositiveIntegerField(),
        ),
    ]
