# Generated by Django 5.0.6 on 2025-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_reclamation_machine_downtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='operating_time',
            field=models.PositiveIntegerField(),
        ),
    ]
