# Generated by Django 5.0.6 on 2025-02-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_reclamation_operating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
